### ISSUE TITLE
Implement Middleware partial probe timing

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/active_endpoint#6]
Need to implement probe timing for `active_record` and `active_dispatcher`, separately. Also need to pay attention to envs and assets loading .

**Comment by artemasmith** [comment]
Take this one.

**Comment by khusnetdinov** [comment]
https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler_rails/railtie.rb#L46

**Comment by khusnetdinov** [comment]
Not actual
